### ISSUE TITLE
providing datasets

### ISSUE THREAD

**Issue by amy-hyunji** [richarddwang/electra_pytorch#1]
Hi, thanks for the great codes!

I am trying to train electra from scratch using your codes here. 
Could you upload the datasets you used on training? (Drives, links, etc..)
I just wanted to make sure that I get the same results before trying other experiments.

Thanks :)

**Comment by richarddwang** [comment]
Hi, all datasets I used here coming from huggingface/nlp, which you only need to execute the code and it will download and preprocess for you, few days needed I guess.

**Comment by amy-hyunji** [comment]
Thanks!
