### ISSUE TITLE
RAM usage during training

### ISSUE THREAD

**Issue by Tiiiger** [richarddwang/electra_pytorch#10]
hi @richarddwang 

Thank you for putting up this repo. This is truly great work.

I want to ask the environment you used to run this code. How much CPU RAM did you use?

I tried to run the training with 50GB RAM but got OOM after 10K steps. 

Is this expected?

**Comment by richarddwang** [comment]
Hi @Tiiiger, 
I didn't be aware of CPU RAM, but I can train it on a server with 4*16GB DDR4.

**Comment by amritalok** [comment]
@richarddwang Can you share your system setup? I am trying to train this on 2080ti but a batch size of 128 doesn't fit on the GPU. How were you able to run a batch size of 128?

**Comment by richarddwang** [comment]
For "ELECTRA-small",
I can train it on a server that has

CPU: silver4116@2.10GHz*2 (24 cores)
Memory: DDR4 8GB*12
GPU: GTX1080Ti*4
and use only one GPU of it.

The peak cuda memory is about 1G.

**Comment by amritalok** [comment]
Thanks!  I am training on a cluster with 2080ti and I get the CUDA memory error. Any suggestions on what could be wrong?
I am using the same setup as yours.

**Comment by richarddwang** [comment]
Sorry for the late reply.
I retest the code and it still work. (cuda:3 used in the following result)
![image](https://user-images.githubusercontent.com/17963619/111952222-c462fa00-8b1f-11eb-86c9-c28ac4c07713.png)

I haven't came up with anything that might get you cuda OOM error.
But if in your case, I may 

- Run notebook and use ipdb to figure out which part/line results in error.
- Run on Colab and see if it makes different. (Although I haven't tried on Colab)

**Comment by amritalok** [comment]
I did try on Colab which gave the memory error. I'll give it a shot with ipdb. Thanks a lot!

**Comment by richarddwang** [comment]
Please tag me if there is any found problems. Close the issue.
