### ISSUE TITLE
ipython package is missing

### ISSUE THREAD

**Issue by PhilipMay** [richarddwang/electra_pytorch#13]
`pretrain.py` imports ipython but it is not given here
https://github.com/richarddwang/electra_pytorch/blob/9b2533e62cd1b6126feca323fb7b48480b8c2df0/requirements.txt#L7

**Comment by richarddwang** [comment]
Thanks you ! I wasn't aware of it.
I have added jupyter to requirements.txt.

Please tag me if you still see the same problem.
