### ISSUE TITLE
Error: `ELECTRAModel` object has no attribute `to_native_fp16`

### ISSUE THREAD

**Issue by PhilipMay** [richarddwang/electra_pytorch#16]
Hi,
after installing the python packages like you say I am getting this error:
`ELECTRAModel` object has no attribute `to_native_fp16`

For details see screenshot below (sorry, I can not copy text - just do screenshots in that environment).

![grafik](https://user-images.githubusercontent.com/229382/114154114-58a2ce80-9920-11eb-9fd1-2dc11204524b.png)

**Comment by richarddwang** [comment]
fastai has renamed `to_native_fp16` to `to_fp16`.
I have commited a change to `requirements.txt`, you can either modify the method name yourself or downgrade fastai to the version specified in `requirements.txt`

Feel free to tag me if you still have the same problem.
