### ISSUE TITLE
Pretrain does not save the model.

### ISSUE THREAD

**Issue by PhilipMay** [richarddwang/electra_pytorch#19]
Hi,

I am starting a pretrain with just 100 iterations like so: `learn.fit(9999, cbs=[lr_shedule])`

But the model is not saved to './checkpoints/pretrain'.

I did specify (as you did) the following for Learner:
```python
                path='./checkpoints',
                model_dir='pretrain',
```

Do I have to manualy save the model?

**Comment by richarddwang** [comment]
- Make sure you include `RunSteps` which save models automatically for you
https://github.com/richarddwang/electra_pytorch/blob/8f6ac2c7efc246a4f6275f82d8417e88d76de046/pretrain.py#L388-L397

- Make sure `c.steps==100`

- comment out `RunSteps` and rerun to see if there is any error, b/c sometime `RunSteps` intercepts the error but there is something went wrong.

**Comment by PhilipMay** [comment]
That works. Thanks.
Closing this again...
