### ISSUE TITLE
Small typo in the README.md

### ISSUE THREAD

**Issue by AminTaheri23** [richarddwang/electra_pytorch#24]
Hi, Thank you for the awesome repository.

There is a small typo in the second table. Row (ELECTRA-Small++) and Col (RTE) should be 63.6, not 6.36. 

Thank you again. 

![image](https://user-images.githubusercontent.com/30533823/114598261-f42c9a00-9ca6-11eb-93ab-bc23a37deb05.png)

**Comment by richarddwang** [comment]
Fixed. Thanks you.
