### ISSUE TITLE
Is multi_task.py in a working state and if so how should one use it?

### ISSUE THREAD

**Issue by lucaguarro** [richarddwang/electra_pytorch#27]
I am looking to train a transformer for a multi-task classification problem and I happened to see multi_task.py within your _utils folder and was curious if it could be useful for my purposes.

I have a problem where I have the texts of novels and I want to train a classifier to classify 1) its genre and 2) its successfulness in hopes that doing both together would help each individual task. Thus my question is if your script would be applicable for said scenario and if so how can I use it?

**Comment by richarddwang** [comment]
It is a leftover developed long time ago,
I am afraid that it no longer works now.
