### ISSUE TITLE
Relative importance of different "tricks" in README

### ISSUE THREAD

**Issue by vmurahari3** [richarddwang/electra_pytorch#35]
Thank you for the brilliant repository! You list some important tricks which are necessary to reproduce performance. In your experience, which of those tricks are critical for matching the released GLUE scores? 

On a cursory glance. seems like reordering the sentences to augment the dataset for STS tasks seems to be a critical detail. I was wondering if that also aligns with your experience in running these models?

**Comment by richarddwang** [comment]
I didn't do ablation study for each point so I can't tell you anything for sure.

In my experience, the data augmentation for fine-tuning STS and MRPC often provides slightly better performance.
