### ISSUE TITLE
NameError: name 'sort_by_run' is not defined

### ISSUE THREAD

**Issue by tomo-logbii** [richarddwang/electra_pytorch#36]
Hi!! When executing the command `python pretrain.py` got the following error.
<img width="898" alt="Screen Shot 2023-03-17 at 2 23 11" src="https://user-images.githubusercontent.com/110445406/225703712-1e54ec62-7e43-4cd1-b381-889527aca21c.png">

I would be happy if you could reply to me when you know something and have a time.

**Comment by richarddwang** [comment]
Hi,

This seems to be a version problem, you can try downgrading `fastcore`. https://github.com/richarddwang/electra_pytorch/issues/26#issuecomment-1354116226

**Comment by tomo-logbii** [comment]
@richarddwang 
That works! Thanks a lot!!😁
