### ISSUE TITLE
duration of training

### ISSUE THREAD

**Issue by amy-hyunji** [richarddwang/electra_pytorch#4]
Hi, I was wondering if we have to train for 10000 epochs as the default setting of your code to get the result. In official electra implementation, it trained for 1000000 steps so 10000 epochs seemed too long. (by the printed value it seems like there are 273193 steps for each epoch) Also, when training electra-small the save points seemed to be 0.0625*(10**6). Is this number related to the step number? 
Thanks :)

**Comment by richarddwang** [comment]
Hi @amy-hyunji , thanks for your interest!
Because fastai didn't provide user a way to run steps instead of epochs (tell me plz if there is any), so I write a callback `RunSteps` which will stop training when 10**6 steps are completed.
So the number of epochs is just any large enough integer.
