### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by wangyu1997** [richarddwang/electra_pytorch#7]
![image](https://user-images.githubusercontent.com/15991233/95644528-da3caf80-0ae9-11eb-9c88-3d8d85ab51d5.png)
Cannot found modeling file in project .

**Comment by richarddwang** [comment]
Hi @wangyu1997 ,
Can you check if you set `my_model` to `True` ? It should be set to `False` as the default, that option is for my personal research's use.
You many also want to check if your copy are up-to-date.

**Comment by richarddwang** [comment]
Since it is stale. I'll close this issue.
Tag me if you want to reopen the issue.
